package com.doerit.doerdb.db.templates;

import com.doerit.doerdb.db.MySQL;

public class MySQLQueryTemplates {

    public static final String PLACEHOLDER_DATABASE_NAME = "[DatabaseName]";
    public static final String PLACEHOLDER_TABLE_NAME = "[TableName]";
    public static final String PLACEHOLDER_TRIGGER_NAME = "[TriggerName]";

    public static final String QUERY_ALL_TABLES = MySQL.SQL_SELECT_CLAUSE + MySQL.SQL_SPACE + MySQL.SQL_CONTENT_TABLE_NAME + MySQL.SQL_SPACE + MySQL.SQL_FROM_CLAUSE + MySQL.SQL_SPACE + MySQL.SQL_CONTENT_INFORMATION_SCHEMA_TABLES + MySQL.SQL_SPACE +
            MySQL.SQL_WHERE_CLAUSE + MySQL.SQL_SPACE +
            MySQL.SQL_INTERNAL_QUOTES + MySQL.SQL_CONTENT_TABLE_SCHEMA + MySQL.SQL_INTERNAL_QUOTES + MySQL.SQL_EQUATOR + MySQL.SQL_EXTERNAL_QUOTES + PLACEHOLDER_DATABASE_NAME + MySQL.SQL_EXTERNAL_QUOTES;

    public static final String QUERY_TABLE_EXISTS = MySQL.SQL_SELECT_CLAUSE + MySQL.SQL_SPACE + "*" + MySQL.SQL_SPACE + MySQL.SQL_FROM_CLAUSE + MySQL.SQL_SPACE + MySQL.SQL_CONTENT_INFORMATION_SCHEMA_TABLES + MySQL.SQL_SPACE +
            MySQL.SQL_WHERE_CLAUSE + MySQL.SQL_SPACE +
            MySQL.SQL_INTERNAL_QUOTES + MySQL.SQL_CONTENT_TABLE_SCHEMA + MySQL.SQL_INTERNAL_QUOTES + MySQL.SQL_EQUATOR + MySQL.SQL_EXTERNAL_QUOTES + PLACEHOLDER_DATABASE_NAME + MySQL.SQL_EXTERNAL_QUOTES + MySQL.SQL_SPACE + MySQL.SQL_AND_OPERATOR + MySQL.SQL_SPACE +
            MySQL.SQL_INTERNAL_QUOTES + MySQL.SQL_CONTENT_TABLE_NAME + MySQL.SQL_INTERNAL_QUOTES + MySQL.SQL_EQUATOR + MySQL.SQL_EXTERNAL_QUOTES + PLACEHOLDER_TABLE_NAME + MySQL.SQL_EXTERNAL_QUOTES;

    public static final String QUERY_TRIGGER_EXISTS = MySQL.SQL_SELECT_CLAUSE + MySQL.SQL_SPACE +
            "1" + MySQL.SQL_SPACE +
            MySQL.SQL_FROM_CLAUSE + MySQL.SQL_SPACE + "information_schema.triggers" + MySQL.SQL_SPACE +
            MySQL.SQL_WHERE_CLAUSE + MySQL.SQL_SPACE +
            MySQL.SQL_INTERNAL_QUOTES + "trigger_schema" + MySQL.SQL_INTERNAL_QUOTES + MySQL.SQL_EQUATOR +  MySQL.SQL_EXTERNAL_QUOTES + PLACEHOLDER_DATABASE_NAME + MySQL.SQL_EXTERNAL_QUOTES + MySQL.SQL_SPACE + MySQL.SQL_AND_OPERATOR + MySQL.SQL_SPACE +
            MySQL.SQL_INTERNAL_QUOTES + "trigger_name" + MySQL.SQL_INTERNAL_QUOTES + MySQL.SQL_EQUATOR +  MySQL.SQL_EXTERNAL_QUOTES + PLACEHOLDER_TRIGGER_NAME + MySQL.SQL_EXTERNAL_QUOTES;

    public static final String QUERY_ALL_COLUMNS = MySQL.SQL_SHOW_CLAUSE + MySQL.SQL_SPACE + MySQL.SQL_CONTENT_COLUMNS + MySQL.SQL_SPACE + MySQL.SQL_FROM_CLAUSE + MySQL.SQL_SPACE +
            MySQL.SQL_INTERNAL_QUOTES + PLACEHOLDER_TABLE_NAME + MySQL.SQL_INTERNAL_QUOTES;

}
